[versions]
# libraries

# plugins
intelliJPlatform = "2.1.0"
kotlin = "2.1.0"

[libraries]

[plugins]
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
